name: tv_series
version: 1.0.0
description: TV series feature module for Ditonton workspace.
publish_to: none
resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.41.0'

dependencies:
  flutter:
    sdk: flutter
  core: ^1.0.0
  dartz: ^0.10.1
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  provider: ^6.1.5+1
  get_it: ^9.2.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  mockito: ^5.6.3
  build_runner: ^2.11.1

