// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i17;
import 'dart:convert' as _i41;
import 'dart:typed_data' as _i42;
import 'dart:ui' as _i35;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ditonton/common/failure.dart' as _i18;
import 'package:ditonton/common/state_enum.dart' as _i34;
import 'package:ditonton/data/datasources/db/database_helper.dart' as _i39;
import 'package:ditonton/data/datasources/movie_local_data_source.dart' as _i23;
import 'package:ditonton/data/datasources/movie_remote_data_source.dart'
    as _i21;
import 'package:ditonton/data/datasources/tv_series_local_data_source.dart'
    as _i29;
import 'package:ditonton/data/datasources/tv_series_remote_data_source.dart'
    as _i27;
import 'package:ditonton/data/models/movie_detail_model.dart' as _i3;
import 'package:ditonton/data/models/movie_model.dart' as _i22;
import 'package:ditonton/data/models/movie_table.dart' as _i24;
import 'package:ditonton/data/models/tv_series_detail_model.dart' as _i4;
import 'package:ditonton/data/models/tv_series_model.dart' as _i28;
import 'package:ditonton/data/models/tv_series_table.dart' as _i30;
import 'package:ditonton/domain/entities/movie.dart' as _i19;
import 'package:ditonton/domain/entities/movie_detail.dart' as _i20;
import 'package:ditonton/domain/entities/tv_series.dart' as _i26;
import 'package:ditonton/domain/entities/tv_series_detail.dart' as _i14;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i16;
import 'package:ditonton/domain/repositories/tv_series_repository.dart' as _i5;
import 'package:ditonton/domain/usecases/get_on_the_air_tv_series.dart' as _i6;
import 'package:ditonton/domain/usecases/get_popular_tv_series.dart' as _i7;
import 'package:ditonton/domain/usecases/get_top_rated_tv_series.dart' as _i8;
import 'package:ditonton/domain/usecases/get_tv_series_detail.dart' as _i9;
import 'package:ditonton/domain/usecases/get_tv_series_recommendations.dart'
    as _i10;
import 'package:ditonton/domain/usecases/get_watchlist_status_tv_series.dart'
    as _i11;
import 'package:ditonton/domain/usecases/get_watchlist_tv_series.dart' as _i32;
import 'package:ditonton/domain/usecases/remove_watchlist_tv_series.dart'
    as _i13;
import 'package:ditonton/domain/usecases/save_watchlist_tv_series.dart' as _i12;
import 'package:ditonton/domain/usecases/search_tv_series.dart' as _i31;
import 'package:ditonton/presentation/provider/on_the_air_tv_series_notifier.dart'
    as _i33;
import 'package:ditonton/presentation/provider/popular_tv_series_notifier.dart'
    as _i36;
import 'package:ditonton/presentation/provider/top_rated_tv_series_notifier.dart'
    as _i37;
import 'package:ditonton/presentation/provider/tv_series_detail_notifier.dart'
    as _i38;
import 'package:http/http.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i25;
import 'package:sqflite/sqflite.dart' as _i40;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailResponse_1 extends _i1.SmartFake
    implements _i3.MovieDetailResponse {
  _FakeMovieDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvSeriesDetailResponse_2 extends _i1.SmartFake
    implements _i4.TvSeriesDetailResponse {
  _FakeTvSeriesDetailResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvSeriesRepository_3 extends _i1.SmartFake
    implements _i5.TvSeriesRepository {
  _FakeTvSeriesRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetOnTheAirTvSeries_4 extends _i1.SmartFake
    implements _i6.GetOnTheAirTvSeries {
  _FakeGetOnTheAirTvSeries_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularTvSeries_5 extends _i1.SmartFake
    implements _i7.GetPopularTvSeries {
  _FakeGetPopularTvSeries_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedTvSeries_6 extends _i1.SmartFake
    implements _i8.GetTopRatedTvSeries {
  _FakeGetTopRatedTvSeries_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTvSeriesDetail_7 extends _i1.SmartFake
    implements _i9.GetTvSeriesDetail {
  _FakeGetTvSeriesDetail_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTvSeriesRecommendations_8 extends _i1.SmartFake
    implements _i10.GetTvSeriesRecommendations {
  _FakeGetTvSeriesRecommendations_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchlistStatusTvSeries_9 extends _i1.SmartFake
    implements _i11.GetWatchlistStatusTvSeries {
  _FakeGetWatchlistStatusTvSeries_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlistTvSeries_10 extends _i1.SmartFake
    implements _i12.SaveWatchlistTvSeries {
  _FakeSaveWatchlistTvSeries_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlistTvSeries_11 extends _i1.SmartFake
    implements _i13.RemoveWatchlistTvSeries {
  _FakeRemoveWatchlistTvSeries_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvSeriesDetail_12 extends _i1.SmartFake
    implements _i14.TvSeriesDetail {
  _FakeTvSeriesDetail_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_13 extends _i1.SmartFake implements _i15.Response {
  _FakeResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_14 extends _i1.SmartFake
    implements _i15.StreamedResponse {
  _FakeStreamedResponse_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i16.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.Future<_i2.Either<_i18.Failure, List<_i19.Movie>>>
  getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue:
                _i17.Future<_i2.Either<_i18.Failure, List<_i19.Movie>>>.value(
                  _FakeEither_0<_i18.Failure, List<_i19.Movie>>(
                    this,
                    Invocation.method(#getNowPlayingMovies, []),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, List<_i19.Movie>>>);

  @override
  _i17.Future<_i2.Either<_i18.Failure, List<_i19.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue:
                _i17.Future<_i2.Either<_i18.Failure, List<_i19.Movie>>>.value(
                  _FakeEither_0<_i18.Failure, List<_i19.Movie>>(
                    this,
                    Invocation.method(#getPopularMovies, []),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, List<_i19.Movie>>>);

  @override
  _i17.Future<_i2.Either<_i18.Failure, List<_i19.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue:
                _i17.Future<_i2.Either<_i18.Failure, List<_i19.Movie>>>.value(
                  _FakeEither_0<_i18.Failure, List<_i19.Movie>>(
                    this,
                    Invocation.method(#getTopRatedMovies, []),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, List<_i19.Movie>>>);

  @override
  _i17.Future<_i2.Either<_i18.Failure, _i20.MovieDetail>> getMovieDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue:
                _i17.Future<_i2.Either<_i18.Failure, _i20.MovieDetail>>.value(
                  _FakeEither_0<_i18.Failure, _i20.MovieDetail>(
                    this,
                    Invocation.method(#getMovieDetail, [id]),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, _i20.MovieDetail>>);

  @override
  _i17.Future<_i2.Either<_i18.Failure, List<_i19.Movie>>>
  getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue:
                _i17.Future<_i2.Either<_i18.Failure, List<_i19.Movie>>>.value(
                  _FakeEither_0<_i18.Failure, List<_i19.Movie>>(
                    this,
                    Invocation.method(#getMovieRecommendations, [id]),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, List<_i19.Movie>>>);

  @override
  _i17.Future<_i2.Either<_i18.Failure, List<_i19.Movie>>> searchMovies(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue:
                _i17.Future<_i2.Either<_i18.Failure, List<_i19.Movie>>>.value(
                  _FakeEither_0<_i18.Failure, List<_i19.Movie>>(
                    this,
                    Invocation.method(#searchMovies, [query]),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, List<_i19.Movie>>>);

  @override
  _i17.Future<_i2.Either<_i18.Failure, String>> saveWatchlist(
    _i20.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [movie]),
            returnValue: _i17.Future<_i2.Either<_i18.Failure, String>>.value(
              _FakeEither_0<_i18.Failure, String>(
                this,
                Invocation.method(#saveWatchlist, [movie]),
              ),
            ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, String>>);

  @override
  _i17.Future<_i2.Either<_i18.Failure, String>> removeWatchlist(
    _i20.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i17.Future<_i2.Either<_i18.Failure, String>>.value(
              _FakeEither_0<_i18.Failure, String>(
                this,
                Invocation.method(#removeWatchlist, [movie]),
              ),
            ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, String>>);

  @override
  _i17.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<_i2.Either<_i18.Failure, List<_i19.Movie>>>
  getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue:
                _i17.Future<_i2.Either<_i18.Failure, List<_i19.Movie>>>.value(
                  _FakeEither_0<_i18.Failure, List<_i19.Movie>>(
                    this,
                    Invocation.method(#getWatchlistMovies, []),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, List<_i19.Movie>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i21.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.Future<List<_i22.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue: _i17.Future<List<_i22.MovieModel>>.value(
              <_i22.MovieModel>[],
            ),
          )
          as _i17.Future<List<_i22.MovieModel>>);

  @override
  _i17.Future<List<_i22.MovieModel>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue: _i17.Future<List<_i22.MovieModel>>.value(
              <_i22.MovieModel>[],
            ),
          )
          as _i17.Future<List<_i22.MovieModel>>);

  @override
  _i17.Future<List<_i22.MovieModel>> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue: _i17.Future<List<_i22.MovieModel>>.value(
              <_i22.MovieModel>[],
            ),
          )
          as _i17.Future<List<_i22.MovieModel>>);

  @override
  _i17.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue: _i17.Future<_i3.MovieDetailResponse>.value(
              _FakeMovieDetailResponse_1(
                this,
                Invocation.method(#getMovieDetail, [id]),
              ),
            ),
          )
          as _i17.Future<_i3.MovieDetailResponse>);

  @override
  _i17.Future<List<_i22.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue: _i17.Future<List<_i22.MovieModel>>.value(
              <_i22.MovieModel>[],
            ),
          )
          as _i17.Future<List<_i22.MovieModel>>);

  @override
  _i17.Future<List<_i22.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue: _i17.Future<List<_i22.MovieModel>>.value(
              <_i22.MovieModel>[],
            ),
          )
          as _i17.Future<List<_i22.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i23.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.Future<String> insertWatchlist(_i24.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [movie]),
            returnValue: _i17.Future<String>.value(
              _i25.dummyValue<String>(
                this,
                Invocation.method(#insertWatchlist, [movie]),
              ),
            ),
          )
          as _i17.Future<String>);

  @override
  _i17.Future<String> removeWatchlist(_i24.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i17.Future<String>.value(
              _i25.dummyValue<String>(
                this,
                Invocation.method(#removeWatchlist, [movie]),
              ),
            ),
          )
          as _i17.Future<String>);

  @override
  _i17.Future<_i24.MovieTable?> getMovieById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieById, [id]),
            returnValue: _i17.Future<_i24.MovieTable?>.value(),
          )
          as _i17.Future<_i24.MovieTable?>);

  @override
  _i17.Future<List<_i24.MovieTable>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue: _i17.Future<List<_i24.MovieTable>>.value(
              <_i24.MovieTable>[],
            ),
          )
          as _i17.Future<List<_i24.MovieTable>>);
}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i1.Mock
    implements _i5.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>>
  getOnTheAirTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAirTvSeries, []),
            returnValue:
                _i17.Future<
                  _i2.Either<_i18.Failure, List<_i26.TvSeries>>
                >.value(
                  _FakeEither_0<_i18.Failure, List<_i26.TvSeries>>(
                    this,
                    Invocation.method(#getOnTheAirTvSeries, []),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>>);

  @override
  _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>>
  getPopularTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTvSeries, []),
            returnValue:
                _i17.Future<
                  _i2.Either<_i18.Failure, List<_i26.TvSeries>>
                >.value(
                  _FakeEither_0<_i18.Failure, List<_i26.TvSeries>>(
                    this,
                    Invocation.method(#getPopularTvSeries, []),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>>);

  @override
  _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>>
  getTopRatedTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTvSeries, []),
            returnValue:
                _i17.Future<
                  _i2.Either<_i18.Failure, List<_i26.TvSeries>>
                >.value(
                  _FakeEither_0<_i18.Failure, List<_i26.TvSeries>>(
                    this,
                    Invocation.method(#getTopRatedTvSeries, []),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>>);

  @override
  _i17.Future<_i2.Either<_i18.Failure, _i14.TvSeriesDetail>> getTvSeriesDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesDetail, [id]),
            returnValue:
                _i17.Future<
                  _i2.Either<_i18.Failure, _i14.TvSeriesDetail>
                >.value(
                  _FakeEither_0<_i18.Failure, _i14.TvSeriesDetail>(
                    this,
                    Invocation.method(#getTvSeriesDetail, [id]),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, _i14.TvSeriesDetail>>);

  @override
  _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>>
  getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesRecommendations, [id]),
            returnValue:
                _i17.Future<
                  _i2.Either<_i18.Failure, List<_i26.TvSeries>>
                >.value(
                  _FakeEither_0<_i18.Failure, List<_i26.TvSeries>>(
                    this,
                    Invocation.method(#getTvSeriesRecommendations, [id]),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>>);

  @override
  _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>> searchTvSeries(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvSeries, [query]),
            returnValue:
                _i17.Future<
                  _i2.Either<_i18.Failure, List<_i26.TvSeries>>
                >.value(
                  _FakeEither_0<_i18.Failure, List<_i26.TvSeries>>(
                    this,
                    Invocation.method(#searchTvSeries, [query]),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>>);

  @override
  _i17.Future<_i2.Either<_i18.Failure, String>> saveWatchlistTvSeries(
    _i14.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlistTvSeries, [tvSeries]),
            returnValue: _i17.Future<_i2.Either<_i18.Failure, String>>.value(
              _FakeEither_0<_i18.Failure, String>(
                this,
                Invocation.method(#saveWatchlistTvSeries, [tvSeries]),
              ),
            ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, String>>);

  @override
  _i17.Future<_i2.Either<_i18.Failure, String>> removeWatchlistTvSeries(
    _i14.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlistTvSeries, [tvSeries]),
            returnValue: _i17.Future<_i2.Either<_i18.Failure, String>>.value(
              _FakeEither_0<_i18.Failure, String>(
                this,
                Invocation.method(#removeWatchlistTvSeries, [tvSeries]),
              ),
            ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, String>>);

  @override
  _i17.Future<bool> isAddedToWatchlistTvSeries(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlistTvSeries, [id]),
            returnValue: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>>
  getWatchlistTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTvSeries, []),
            returnValue:
                _i17.Future<
                  _i2.Either<_i18.Failure, List<_i26.TvSeries>>
                >.value(
                  _FakeEither_0<_i18.Failure, List<_i26.TvSeries>>(
                    this,
                    Invocation.method(#getWatchlistTvSeries, []),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>>);
}

/// A class which mocks [TvSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRemoteDataSource extends _i1.Mock
    implements _i27.TvSeriesRemoteDataSource {
  MockTvSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.Future<List<_i28.TvSeriesModel>> getOnTheAirTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAirTvSeries, []),
            returnValue: _i17.Future<List<_i28.TvSeriesModel>>.value(
              <_i28.TvSeriesModel>[],
            ),
          )
          as _i17.Future<List<_i28.TvSeriesModel>>);

  @override
  _i17.Future<List<_i28.TvSeriesModel>> getPopularTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTvSeries, []),
            returnValue: _i17.Future<List<_i28.TvSeriesModel>>.value(
              <_i28.TvSeriesModel>[],
            ),
          )
          as _i17.Future<List<_i28.TvSeriesModel>>);

  @override
  _i17.Future<List<_i28.TvSeriesModel>> getTopRatedTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTvSeries, []),
            returnValue: _i17.Future<List<_i28.TvSeriesModel>>.value(
              <_i28.TvSeriesModel>[],
            ),
          )
          as _i17.Future<List<_i28.TvSeriesModel>>);

  @override
  _i17.Future<_i4.TvSeriesDetailResponse> getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesDetail, [id]),
            returnValue: _i17.Future<_i4.TvSeriesDetailResponse>.value(
              _FakeTvSeriesDetailResponse_2(
                this,
                Invocation.method(#getTvSeriesDetail, [id]),
              ),
            ),
          )
          as _i17.Future<_i4.TvSeriesDetailResponse>);

  @override
  _i17.Future<List<_i28.TvSeriesModel>> getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesRecommendations, [id]),
            returnValue: _i17.Future<List<_i28.TvSeriesModel>>.value(
              <_i28.TvSeriesModel>[],
            ),
          )
          as _i17.Future<List<_i28.TvSeriesModel>>);

  @override
  _i17.Future<List<_i28.TvSeriesModel>> searchTvSeries(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvSeries, [query]),
            returnValue: _i17.Future<List<_i28.TvSeriesModel>>.value(
              <_i28.TvSeriesModel>[],
            ),
          )
          as _i17.Future<List<_i28.TvSeriesModel>>);
}

/// A class which mocks [TvSeriesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesLocalDataSource extends _i1.Mock
    implements _i29.TvSeriesLocalDataSource {
  MockTvSeriesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.Future<String> insertWatchlist(_i30.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [tvSeries]),
            returnValue: _i17.Future<String>.value(
              _i25.dummyValue<String>(
                this,
                Invocation.method(#insertWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i17.Future<String>);

  @override
  _i17.Future<String> removeWatchlist(_i30.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tvSeries]),
            returnValue: _i17.Future<String>.value(
              _i25.dummyValue<String>(
                this,
                Invocation.method(#removeWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i17.Future<String>);

  @override
  _i17.Future<_i30.TvSeriesTable?> getTvSeriesById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesById, [id]),
            returnValue: _i17.Future<_i30.TvSeriesTable?>.value(),
          )
          as _i17.Future<_i30.TvSeriesTable?>);

  @override
  _i17.Future<List<_i30.TvSeriesTable>> getWatchlistTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTvSeries, []),
            returnValue: _i17.Future<List<_i30.TvSeriesTable>>.value(
              <_i30.TvSeriesTable>[],
            ),
          )
          as _i17.Future<List<_i30.TvSeriesTable>>);
}

/// A class which mocks [GetOnTheAirTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOnTheAirTvSeries extends _i1.Mock
    implements _i6.GetOnTheAirTvSeries {
  MockGetOnTheAirTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i17.Future<
                  _i2.Either<_i18.Failure, List<_i26.TvSeries>>
                >.value(
                  _FakeEither_0<_i18.Failure, List<_i26.TvSeries>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>>);
}

/// A class which mocks [GetPopularTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTvSeries extends _i1.Mock
    implements _i7.GetPopularTvSeries {
  MockGetPopularTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i17.Future<
                  _i2.Either<_i18.Failure, List<_i26.TvSeries>>
                >.value(
                  _FakeEither_0<_i18.Failure, List<_i26.TvSeries>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>>);
}

/// A class which mocks [GetTopRatedTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedTvSeries extends _i1.Mock
    implements _i8.GetTopRatedTvSeries {
  MockGetTopRatedTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i17.Future<
                  _i2.Either<_i18.Failure, List<_i26.TvSeries>>
                >.value(
                  _FakeEither_0<_i18.Failure, List<_i26.TvSeries>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>>);
}

/// A class which mocks [GetTvSeriesDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvSeriesDetail extends _i1.Mock implements _i9.GetTvSeriesDetail {
  MockGetTvSeriesDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i17.Future<_i2.Either<_i18.Failure, _i14.TvSeriesDetail>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i17.Future<
                  _i2.Either<_i18.Failure, _i14.TvSeriesDetail>
                >.value(
                  _FakeEither_0<_i18.Failure, _i14.TvSeriesDetail>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, _i14.TvSeriesDetail>>);
}

/// A class which mocks [GetTvSeriesRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvSeriesRecommendations extends _i1.Mock
    implements _i10.GetTvSeriesRecommendations {
  MockGetTvSeriesRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i17.Future<
                  _i2.Either<_i18.Failure, List<_i26.TvSeries>>
                >.value(
                  _FakeEither_0<_i18.Failure, List<_i26.TvSeries>>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>>);
}

/// A class which mocks [SearchTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTvSeries extends _i1.Mock implements _i31.SearchTvSeries {
  MockSearchTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>> execute(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [query]),
            returnValue:
                _i17.Future<
                  _i2.Either<_i18.Failure, List<_i26.TvSeries>>
                >.value(
                  _FakeEither_0<_i18.Failure, List<_i26.TvSeries>>(
                    this,
                    Invocation.method(#execute, [query]),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>>);
}

/// A class which mocks [GetWatchlistStatusTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistStatusTvSeries extends _i1.Mock
    implements _i11.GetWatchlistStatusTvSeries {
  MockGetWatchlistStatusTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i17.Future<bool> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);
}

/// A class which mocks [SaveWatchlistTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistTvSeries extends _i1.Mock
    implements _i12.SaveWatchlistTvSeries {
  MockSaveWatchlistTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i17.Future<_i2.Either<_i18.Failure, String>> execute(
    _i14.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [tvSeries]),
            returnValue: _i17.Future<_i2.Either<_i18.Failure, String>>.value(
              _FakeEither_0<_i18.Failure, String>(
                this,
                Invocation.method(#execute, [tvSeries]),
              ),
            ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, String>>);
}

/// A class which mocks [RemoveWatchlistTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistTvSeries extends _i1.Mock
    implements _i13.RemoveWatchlistTvSeries {
  MockRemoveWatchlistTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i17.Future<_i2.Either<_i18.Failure, String>> execute(
    _i14.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [tvSeries]),
            returnValue: _i17.Future<_i2.Either<_i18.Failure, String>>.value(
              _FakeEither_0<_i18.Failure, String>(
                this,
                Invocation.method(#execute, [tvSeries]),
              ),
            ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, String>>);
}

/// A class which mocks [GetWatchlistTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTvSeries extends _i1.Mock
    implements _i32.GetWatchlistTvSeries {
  MockGetWatchlistTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i17.Future<
                  _i2.Either<_i18.Failure, List<_i26.TvSeries>>
                >.value(
                  _FakeEither_0<_i18.Failure, List<_i26.TvSeries>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i17.Future<_i2.Either<_i18.Failure, List<_i26.TvSeries>>>);
}

/// A class which mocks [OnTheAirTvSeriesNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnTheAirTvSeriesNotifier extends _i1.Mock
    implements _i33.OnTheAirTvSeriesNotifier {
  MockOnTheAirTvSeriesNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GetOnTheAirTvSeries get getOnTheAirTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#getOnTheAirTvSeries),
            returnValue: _FakeGetOnTheAirTvSeries_4(
              this,
              Invocation.getter(#getOnTheAirTvSeries),
            ),
          )
          as _i6.GetOnTheAirTvSeries);

  @override
  _i34.RequestState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i34.RequestState.Empty,
          )
          as _i34.RequestState);

  @override
  List<_i26.TvSeries> get tvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#tvSeries),
            returnValue: <_i26.TvSeries>[],
          )
          as List<_i26.TvSeries>);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i17.Future<void> fetchOnTheAirTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#fetchOnTheAirTvSeries, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  void addListener(_i35.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i35.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PopularTvSeriesNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularTvSeriesNotifier extends _i1.Mock
    implements _i36.PopularTvSeriesNotifier {
  MockPopularTvSeriesNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.GetPopularTvSeries get getPopularTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularTvSeries),
            returnValue: _FakeGetPopularTvSeries_5(
              this,
              Invocation.getter(#getPopularTvSeries),
            ),
          )
          as _i7.GetPopularTvSeries);

  @override
  _i34.RequestState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i34.RequestState.Empty,
          )
          as _i34.RequestState);

  @override
  List<_i26.TvSeries> get tvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#tvSeries),
            returnValue: <_i26.TvSeries>[],
          )
          as List<_i26.TvSeries>);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i17.Future<void> fetchPopularTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPopularTvSeries, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  void addListener(_i35.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i35.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TopRatedTvSeriesNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTvSeriesNotifier extends _i1.Mock
    implements _i37.TopRatedTvSeriesNotifier {
  MockTopRatedTvSeriesNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.GetTopRatedTvSeries get getTopRatedTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedTvSeries),
            returnValue: _FakeGetTopRatedTvSeries_6(
              this,
              Invocation.getter(#getTopRatedTvSeries),
            ),
          )
          as _i8.GetTopRatedTvSeries);

  @override
  _i34.RequestState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i34.RequestState.Empty,
          )
          as _i34.RequestState);

  @override
  List<_i26.TvSeries> get tvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#tvSeries),
            returnValue: <_i26.TvSeries>[],
          )
          as List<_i26.TvSeries>);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i17.Future<void> fetchTopRatedTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTopRatedTvSeries, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  void addListener(_i35.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i35.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TvSeriesDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesDetailNotifier extends _i1.Mock
    implements _i38.TvSeriesDetailNotifier {
  MockTvSeriesDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.GetTvSeriesDetail get getTvSeriesDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getTvSeriesDetail),
            returnValue: _FakeGetTvSeriesDetail_7(
              this,
              Invocation.getter(#getTvSeriesDetail),
            ),
          )
          as _i9.GetTvSeriesDetail);

  @override
  _i10.GetTvSeriesRecommendations get getTvSeriesRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#getTvSeriesRecommendations),
            returnValue: _FakeGetTvSeriesRecommendations_8(
              this,
              Invocation.getter(#getTvSeriesRecommendations),
            ),
          )
          as _i10.GetTvSeriesRecommendations);

  @override
  _i11.GetWatchlistStatusTvSeries get getWatchlistStatusTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchlistStatusTvSeries),
            returnValue: _FakeGetWatchlistStatusTvSeries_9(
              this,
              Invocation.getter(#getWatchlistStatusTvSeries),
            ),
          )
          as _i11.GetWatchlistStatusTvSeries);

  @override
  _i12.SaveWatchlistTvSeries get saveWatchlistTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#saveWatchlistTvSeries),
            returnValue: _FakeSaveWatchlistTvSeries_10(
              this,
              Invocation.getter(#saveWatchlistTvSeries),
            ),
          )
          as _i12.SaveWatchlistTvSeries);

  @override
  _i13.RemoveWatchlistTvSeries get removeWatchlistTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#removeWatchlistTvSeries),
            returnValue: _FakeRemoveWatchlistTvSeries_11(
              this,
              Invocation.getter(#removeWatchlistTvSeries),
            ),
          )
          as _i13.RemoveWatchlistTvSeries);

  @override
  _i14.TvSeriesDetail get tvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#tvSeries),
            returnValue: _FakeTvSeriesDetail_12(
              this,
              Invocation.getter(#tvSeries),
            ),
          )
          as _i14.TvSeriesDetail);

  @override
  _i34.RequestState get tvSeriesState =>
      (super.noSuchMethod(
            Invocation.getter(#tvSeriesState),
            returnValue: _i34.RequestState.Empty,
          )
          as _i34.RequestState);

  @override
  List<_i26.TvSeries> get tvSeriesRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#tvSeriesRecommendations),
            returnValue: <_i26.TvSeries>[],
          )
          as List<_i26.TvSeries>);

  @override
  _i34.RequestState get recommendationState =>
      (super.noSuchMethod(
            Invocation.getter(#recommendationState),
            returnValue: _i34.RequestState.Empty,
          )
          as _i34.RequestState);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get isAddedToWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#isAddedToWatchlist),
            returnValue: false,
          )
          as bool);

  @override
  String get watchlistMessage =>
      (super.noSuchMethod(
            Invocation.getter(#watchlistMessage),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#watchlistMessage),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i17.Future<void> fetchTvSeriesDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTvSeriesDetail, [id]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> addWatchlist(_i14.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#addWatchlist, [tvSeries]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> removeFromWatchlist(_i14.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromWatchlist, [tvSeries]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> loadWatchlistStatus(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#loadWatchlistStatus, [id]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  void addListener(_i35.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i35.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i39.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.Future<_i40.Database?> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i17.Future<_i40.Database?>.value(),
          )
          as _i17.Future<_i40.Database?>);

  @override
  _i17.Future<int> insertWatchlist(_i24.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [movie]),
            returnValue: _i17.Future<int>.value(0),
          )
          as _i17.Future<int>);

  @override
  _i17.Future<int> removeWatchlist(_i24.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i17.Future<int>.value(0),
          )
          as _i17.Future<int>);

  @override
  _i17.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieById, [id]),
            returnValue: _i17.Future<Map<String, dynamic>?>.value(),
          )
          as _i17.Future<Map<String, dynamic>?>);

  @override
  _i17.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue: _i17.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i17.Future<List<Map<String, dynamic>>>);

  @override
  _i17.Future<int> insertTvSeriesWatchlist(_i30.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#insertTvSeriesWatchlist, [tvSeries]),
            returnValue: _i17.Future<int>.value(0),
          )
          as _i17.Future<int>);

  @override
  _i17.Future<int> removeTvSeriesWatchlist(_i30.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#removeTvSeriesWatchlist, [tvSeries]),
            returnValue: _i17.Future<int>.value(0),
          )
          as _i17.Future<int>);

  @override
  _i17.Future<Map<String, dynamic>?> getTvSeriesById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesById, [id]),
            returnValue: _i17.Future<Map<String, dynamic>?>.value(),
          )
          as _i17.Future<Map<String, dynamic>?>);

  @override
  _i17.Future<List<Map<String, dynamic>>> getWatchlistTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTvSeries, []),
            returnValue: _i17.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i17.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i15.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.Future<_i15.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i17.Future<_i15.Response>.value(
              _FakeResponse_13(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i17.Future<_i15.Response>);

  @override
  _i17.Future<_i15.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i17.Future<_i15.Response>.value(
              _FakeResponse_13(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i17.Future<_i15.Response>);

  @override
  _i17.Future<_i15.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i41.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i17.Future<_i15.Response>.value(
              _FakeResponse_13(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i17.Future<_i15.Response>);

  @override
  _i17.Future<_i15.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i41.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i17.Future<_i15.Response>.value(
              _FakeResponse_13(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i17.Future<_i15.Response>);

  @override
  _i17.Future<_i15.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i41.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i17.Future<_i15.Response>.value(
              _FakeResponse_13(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i17.Future<_i15.Response>);

  @override
  _i17.Future<_i15.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i41.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i17.Future<_i15.Response>.value(
              _FakeResponse_13(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i17.Future<_i15.Response>);

  @override
  _i17.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i17.Future<String>.value(
              _i25.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i17.Future<String>);

  @override
  _i17.Future<_i42.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i17.Future<_i42.Uint8List>.value(_i42.Uint8List(0)),
          )
          as _i17.Future<_i42.Uint8List>);

  @override
  _i17.Future<_i15.StreamedResponse> send(_i15.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i17.Future<_i15.StreamedResponse>.value(
              _FakeStreamedResponse_14(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i17.Future<_i15.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
